CREATE TABLE Users
(
    userId    INTEGER      NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nickname  VARCHAR(191) NOT NULL UNIQUE,
    password  VARCHAR(191) NOT NULL,
    createdAt DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updatedAt DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE Posts
(
    postId    INTEGER       NOT NULL AUTO_INCREMENT PRIMARY KEY,
    UserId    INTEGER       NOT NULL,
    title     VARCHAR(191)  NOT NULL,
    content   VARCHAR(3000) NOT NULL,
    createdAt DATETIME(3)   NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updatedAt DATETIME(3)   NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    FOREIGN KEY (UserId) REFERENCES Users (userId) ON DELETE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE Comments
(
    commentId INTEGER      NOT NULL AUTO_INCREMENT PRIMARY KEY,
    PostId    INTEGER      NOT NULL,
    UserId    INTEGER      NOT NULL,
    comment   VARCHAR(191) NOT NULL,
    createdAt DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updatedAt DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    FOREIGN KEY (PostId) REFERENCES Posts (postId) ON DELETE CASCADE,
    FOREIGN KEY (UserId) REFERENCES Users (userId) ON DELETE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE Likes
(
    likeId    INTEGER     NOT NULL AUTO_INCREMENT PRIMARY KEY,
    PostId    INTEGER     NOT NULL,
    UserId    INTEGER     NOT NULL,
    createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updatedAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    FOREIGN KEY (PostId) REFERENCES Posts (postId) ON DELETE CASCADE,
    FOREIGN KEY (UserId) REFERENCES Users (userId) ON DELETE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;